name: CI
on: [pull_request]
jobs:
  validate-code:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check workspace
        uses: EmbarkStudios/cargo-deny-action@v2
      - name: Check architecture
        run: ./scripts/lint_architecture.sh
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test
