name: CI
on: [push, pull_request]
jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check workspace
        uses: EmbarkStudios/cargo-deny-action@v2
      - name: Check architecture
        run: ./scripts/lint_architecture.sh
      - name: Build release
        run: cargo build --release
